## Método dos Mínimos Quadrados - MMQ

In [ ]:
import numpy as np

A=np.matrix([[1,0,0],
             [0,1,0],
             [0,0,1],
             [1,1,0],
             [0,1,1]])
P=np.eye(5)
Lb=np.matrix([[100],
              [100],
              [100.08],
              [200.04],
              [200]])

In [ ]:
ATA=np.linalg.inv(np.dot(np.dot(A.T,P),A))
ATL=np.dot(np.dot(A.T,P),Lb)
Xa=np.dot(ATA,ATL)
print(Xa)

[[100.025]
 [ 99.99 ]
 [100.045]]


In [ ]:
Xa=np.linalg.inv(A.T*P*A)*(A.T*P*Lb)
print(Xa)

[[100.025]
 [ 99.99 ]
 [100.045]]


In [ ]:
V=A*Xa-Lb
print(V)

[[ 0.025]
 [-0.01 ]
 [-0.035]
 [-0.025]
 [ 0.035]]
