# Operações com matrizes e vetores

Representamos matrizes e vetores através do objeto array. Podemos pensar em arrays unidimensionais como listas de números e arrays bidimensionais como matrizes. 

## Operações aritméticas de matrizes e vetores

As operações de adição (+), subtração (-), divisão (/), multiplicação (*) e exponenciação (**) podem ser realizadas entre arrays e escalares:

In [7]:
import numpy as np

A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
A*2

array([[2, 4],
       [6, 8]])

Quando realizadas entre arrays, essas operações são realizadas elemento a elemento:

In [9]:
A*A

array([[ 1,  4],
       [ 9, 16]])

Podemos também manipular arrays unidimensionais como esperado para vetores, ou seja, em termos de soma de vetores e multiplicação por escalar:

In [10]:
u = np.array([1., -1.])
v = np.array([1.,  1.])
u + v

array([2., 0.])

In [11]:
2*u

array([ 2., -2.])

Multiplicação matricial

A multiplicação matricial possui um operador próprio (@) em Python:

In [12]:
A@A

array([[ 7, 10],
       [15, 22]])

Vamos calcular $\ (2A−I+AB) $  para: <br>
A = \begin{bmatrix}1 & 2\\3 & 4\end{bmatrix} <br> B = \begin{bmatrix}3 & 1\\4 & 0\end{bmatrix}

com $\ I$ sendo a matriz identidade de dimensão dois (como vimos antes na parte de matrizes bloco, as matrizes identidade podem ser construídas com `numpy.eye`):

In [13]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [14]:
A

array([[1, 2],
       [3, 4]])

In [15]:
B = np.array([[3., 1.],
              [4., 0.]])

In [16]:
2. * A - I + A @ B

array([[12.,  5.],
       [31., 10.]])

Transposição de matrizes

In [18]:
A.T

array([[1, 3],
       [2, 4]])

Inversão de matrizes

Matrizes são invertidas com `numpy.linalg.inv`:

In [20]:
Ai = np.linalg.inv(A)
Ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

A matriz inversa $\ A^{−1}$ é tal que: <br>
$\ A^{−1}.A=A.A^{-1}= I $ 

onde $\ I $ é a matriz identidade

In [21]:
Ai @ A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

A menos de erros numéricos, essa parece ser a resposta correta (valores da ordem de $\ 10^{−16} $ são praticamente zero). Vamos checar isso por comparação da multiplicação acima com a matriz identidade (usando a função `numpy.allclose`, que compara arrays a menos de erros numéricos):

In [22]:
np.allclose(Ai @ A, np.eye(2))

True

Lembre-se: nem toda matriz possui inversa! Uma maneira de identificar se uma matriz possui inversa é com o cálculo do rank da mesma (`numpy.linalg.matrix_rank`), que deve ser igual à dimensão do array:

In [23]:
np.linalg.matrix_rank(A)

2

In [24]:
A.ndim

2

# Voltando a propagação de covariancias

Nos vimos que a lei da propagação de covariancias diz que se conhecemos a relação entre variáveis: <br><br>
    $\ A.X+C = Y $ <br><br>
é possível propagar $\Sigma_{X}$ que é a MVC das variáveis independentes para encontrarmos $\Sigma_{Y}$ por meio da seguinte relação: <br><br>
$\ \Sigma_{Y} = D. \Sigma_{X}.D' $ <br>
<br>
onde $\ D$ é a matriz das derivadas parciais de $\ AX $ em relação a $\ X $. <br>
## Exemplo 1: 
Foram realizadas as medidas de  5  direções ($\ d_1 ,  d_2 ,  d_3 ,  d_4 \textrm{ e }  d_5 $ ) com um 
equipamento cuja precisão angular  é de 5”. Pretende-se calcular os ângulos $\ a_1 , a_2 , a_3  \textrm{ e }  
a_4 $ entre essa direções conforme a figura a seguir. Ao se determinar o ângulo entre duas 
direções, qual será a precisão do resultado obtido? 
<img src="ex1.png">

In [31]:
#resolva utilizando os comandos Python para operações matriciais


## Exemplo 2:
Um observador com uma estação total mediu o azimute da direção 01 e a 
distância entre as estações 0 e 1 a partir do ponto 0 cujas coordenadas são (0, 0). Os 
valores obtidos foram respectivamente, $\ A_{01}$ = 60º e $\ d_{01}$ = 2.000 m. Considere que  ele 
utilizou um equipamento cuja precisão angular é de 5” e a linear de  ± 5mm ± 5ppm. 
Quais são as coordenadas do ponto 1 ($\ x_{1} ,y_{1})$ e a respectiva precisão?
    <img src="ex2a.png"> 
    <img src="ex2b.png">

In [ ]:
#resolva utilizando os comandos Python para operações matriciais