# AJUSTAMENTO PARAMÉTRICO
UNIVERSIDADE FEDERAL DA BAHIA <br>
DISCIPLINA: AJUSTAMENTO DE OBSERVAÇÕES GEODÉSICAS B <br>
DOCENTE: MAURO ALIXANDRINI

## Exercício 01
Para determinação precisa da coordenada planimétrica de um ponto utilizando técnica topográfica de trilateração foram medidas distâncias a partir de quatro pontos com coordenadas conhecidas($\ P_1,P_2,P_3,P_4 $\). Foi medido adicionalmente um ângulo ($ \alpha$\) a partir da posição eu se deseja obter no levantamento ($\ P$\). Os dados são descritos conforme o croqui abaixo:
<img src="https://raw.githubusercontent.com/Alixandrini/ENGJ22/main/Aula%204/ex4.png">
As observações constantes com suas respectivas precisões calculadas a partir da Precisão Nominal constante no equipamento utilizado são:

| Observações ($\ L_b$\) | Distância (m) | Desvio padrão ($\ \sigma$\)|
|---------| ---------| ---------| 
|$\ L_{b1}$ | 244.512   | 0.012 |
|$\ L_{b2}$ | 321.570   | 0.016 |
|$\ L_{b3}$ |773.154    | 0.038 |
|$\ L_{b4}$ |279.992    | 0.014 |
|$\ L_{b5}$ |123$^{\circ}$ 38' 01.4"| 2" |

## Resolução
Primeiro vamos entrar com os dados conhecidos, as coordenadas dos pontos e as distâncias. IMPORTANTE: o ângulo será ignorado nessa primeira resolução do exercício:

In [123]:
import math 
#dessa biblioteca utilizaremos a constante pi para conversão do angulo para radianos
#Coordenadas
X1=842.281;
Y1=925.523;
X2=1337.544;
Y2=996.249;
X3=1831.727;
Y3=723.962;
X4=840.408;
Y4=658.345;

#Distâncias (m)
D1=244.512;
D2=321.570;
D3=773.154;
D4=279.992;


O mesmo pode ser feito para os desvios padrão

In [124]:
sigma1=0.012
sigma2=0.016
sigma3=0.038
sigma4=0.014


Agoram vamos voltar ao método paramétrico($\ L_a=F(X_a)$), e lembrar que a condição para usa-lo é obster um sistema de equações onde possamos separar as observações (distâncias e o ângulo nesse caso) dos nossos parâmetros ( Coordenadas do ponto P ($\ X_P, Y_P$).
Podemos utilizar a equação da distância entre dois pontos:
\begin{equation}
D=\sqrt[2]{(X_1-X_2)^2+(Y_1-Y_2)^2}
\end{equation}


Assim o sistema de equações do nosso modelo funcional para a resolução do método paramétrico
fica o seguinte:

\begin{equation}
L_{b1}+\nu_1=\sqrt[2]{(X_1-X_p)^2+(Y_1-Y_p)^2} \\
L_{b2}+\nu_2=\sqrt[2]{(X_2-X_p)^2+(Y_2-Y_p)^2} \\
L_{b3}+\nu_3=\sqrt[2]{(X_3-X_p)^2+(Y_3-Y_p)^2} \\
L_{b4}+\nu_4=\sqrt[2]{(X_4-X_p)^2+(Y_4-Y_p)^2} 
\end{equation}

Agora temos que montar as matrizes necessárias a resolução do sistema de equações normais:
\begin{equation}
N=A^tPA \\
U=A^tPL\\
L=L_0-L_b\\
X=-N^{-1}U\\
X_a=X_0+X\\
\end{equation}
Na ordem precisaremos montar a partir dos dados as matrizes $\ L_b,P,L_0,X_0,A $.

In [125]:
## A matriz Lb é a matriz das observações:
import numpy as np

Lb=np.matrix ([[D1],[D2],[D3],[D4]]);

In [126]:
## A matriz P é a matriz dos pesos, ela é uma matriz quadrada 
##construída a partir do inverso do variância da minhas observações
## no caso temos observações independêntes e por isso nossa matriz P é diagonal:
P=np.matrix ([[(1/sigma1**2), 0, 0, 0],
             [0, (1/sigma2**2), 0, 0],
             [0, 0, (1/sigma3**2), 0],
             [0, 0, 0, (1/sigma4**2)]]);


In [127]:
# A matriz L0 como apresentada na última aula é a aplicação de X0 
# no sistema matemático funcional do nosso problema.
# Então vamos estimar as coordenadas aproximadas do ponto P e aplicar no 
# nosso sistema de equações:
x0=1065;
y0=825;
X0=np.matrix ([[x0],[y0]]);
L0=np.matrix([[(math.sqrt(((X1-x0)**2)+((Y1-y0)**2)))],
              [(math.sqrt(((X2-x0)**2)+((Y2-y0)**2)))],
               [(math.sqrt(((X3-x0)**2)+((Y3-y0)**2)))],
               [(math.sqrt(((X4-x0)**2)+((Y4-y0)**2)))]]);



Por último a matriz A que é resultado da derivada primeira das equações do nosso sistema em relação ao parâmetro ($\ X_{Pa}, Y_{Pa}$).

\begin{equation}
\frac{\partial L_{a1}}{\partial X_{pa}}=-\frac {X_1-X_{pa}}{L_{a1}}\\
\frac{\partial L_{a1}}{\partial Y_{pa}}=-\frac {Y_1-Y_{pa}}{L_{a1}}\\
\frac{\partial L_{a2}}{\partial X_{pa}}=-\frac {X_2-X_{pa}}{L_{a2}}\\
\frac{\partial L_{a2}}{\partial X_{pa}}=-\frac {Y_2-Y_{pa}}{L_{a2}}\\
\frac{\partial L_{a3}}{\partial X_{pa}}=-\frac {X_3-X_{pa}}{L_{a3}}\\
\frac{\partial L_{a3}}{\partial X_{pa}}=-\frac {Y_3-Y_{pa}}{L_{a2}}\\
\frac{\partial L_{a4}}{\partial X_{pa}}=-\frac {X_4-X_{pa}}{L_{a4}}\\
\frac{\partial L_{a4}}{\partial X_{pa}}=-\frac {Y_4-X_{pa}}{L_{a4}}\\
\frac{\partial L_{a5}}{\partial X_{pa}}=-\frac{(X_{P_2}-X_P)}{L_{a2}^2}+\frac{(X_{P_1}-X_P)}{L_{a1}}^2 \\
\frac{\partial L_{a5}}{\partial Y_{pa}}=-\frac{(Y_{P_2}-Y_P)}{L_{a2}^2}+\frac{(Y_{P_1}-Y_P)}{L_{a1}^2}
\end{equation}

Lembrando que o modelo matemático e as derivadas fazem menção aos valores ajustados enquanto no calculo do ajustamento utilizaremos os valores de $\ L_b, X_0 $ para obstermos valores númericos para a matriz A.

In [128]:
# nossa matriz A terá 4 linhas (devido as 4 equações) e 2 colunas (devido aos dois parâmetros)
A=np.zeros((4,2))
A[0][0]=-(X1-X0[0][0])/Lb[0][0]
A[0][1]=-(Y1-X0[1][0])/Lb[0][0]
A[1][0]=-(X2-X0[0][0])/Lb[1][0]
A[1][1]=-(Y2-X0[1][0])/Lb[1][0]
A[2][0]=-(X3-X0[0][0])/Lb[2][0]
A[2][1]=-(Y3-X0[1][0])/Lb[2][0]
A[3][0]=-(X4-X0[0][0])/Lb[3][0]
A[3][1]=-(Y4-X0[1][0])/Lb[3][0]


In [129]:
#aplicando as operações matriciais com o sistema de equações normais obtemos:
L=L0-Lb
N=np.dot(np.dot(A.T,P),A)
print("Matriz N:\n",N)
U=np.dot(np.dot(A.T,P),L)
print("Matriz U:\n",U)
X=-np.dot(np.linalg.inv(N),U)
Xa=X0+X
print("Matriz Xa:\n",Xa)

Matriz N:
 [[12531.50996069  1508.75319901]
 [ 1508.75319901  4100.91197198]]
Matriz U:
 [[-3482.75642797]
 [-1150.21332438]]
Matriz Xa:
 [[1065.25546722]
 [ 825.18648933]]


# Processo Iterativo do Método Paramétrico

In [130]:
X0=Xa

In [131]:
L0=np.matrix([[(math.sqrt(((X1-X0[0][0])**2)+((Y1-X0[1][0])**2)))],
              [(math.sqrt(((X2-X0[0][0])**2)+((Y2-X0[1][0])**2)))],
              [(math.sqrt(((X3-X0[0][0])**2)+((Y3-X0[1][0])**2)))],
              [(math.sqrt(((X4-X0[0][0])**2)+((Y4-X0[1][0])**2)))]]);
A=np.zeros((4,2))
A[0][0]=-(X1-X0[0][0])/Lb[0][0]
A[0][1]=-(Y1-X0[1][0])/Lb[0][0]
A[1][0]=-(X2-X0[0][0])/Lb[1][0]
A[1][1]=-(Y2-X0[1][0])/Lb[1][0]
A[2][0]=-(X3-X0[0][0])/Lb[2][0]
A[2][1]=-(Y3-X0[1][0])/Lb[2][0]
A[3][0]=-(X4-X0[0][0])/Lb[3][0]
A[3][1]=-(Y4-X0[1][0])/Lb[3][0]

In [132]:
L=L0-Lb
N=np.dot(np.dot(A.T,P),A)
print("Matriz N:\n",N)
U=np.dot(np.dot(A.T,P),L)
print("Matriz U:\n",U)
X=np.dot(np.linalg.inv(N),U)
Xa=X0+X
print("Matriz Xa:\n",Xa)

Matriz N:
 [[12546.49612999  1512.39354371]
 [ 1512.39354371  4098.24084511]]
Matriz U:
 [[ 1.96985287]
 [-0.30061944]]
Matriz Xa:
 [[1065.25564079]
 [ 825.18635193]]


In [133]:
X0=Xa
L0=np.matrix([[(math.sqrt(((X1-X0[0][0])**2)+((Y1-X0[1][0])**2)))],
              [(math.sqrt(((X2-X0[0][0])**2)+((Y2-X0[1][0])**2)))],
              [(math.sqrt(((X3-X0[0][0])**2)+((Y3-X0[1][0])**2)))],
              [(math.sqrt(((X4-X0[0][0])**2)+((Y4-X0[1][0])**2)))]]);
A=np.zeros((4,2))
A[0][0]=-(X1-X0[0][0])/Lb[0][0]
A[0][1]=-(Y1-X0[1][0])/Lb[0][0]
A[1][0]=-(X2-X0[0][0])/Lb[1][0]
A[1][1]=-(Y2-X0[1][0])/Lb[1][0]
A[2][0]=-(X3-X0[0][0])/Lb[2][0]
A[2][1]=-(Y3-X0[1][0])/Lb[2][0]
A[3][0]=-(X4-X0[0][0])/Lb[3][0]
A[3][1]=-(Y4-X0[1][0])/Lb[3][0]
L=L0-Lb
N=np.dot(np.dot(A.T,P),A)
print("Matriz N:\n",N)
U=np.dot(np.dot(A.T,P),L)
print("Matriz U:\n",U)
X=-np.dot(np.linalg.inv(N),U)
Xa=X0+X
print("Matriz Xa:\n",Xa)

Matriz N:
 [[12546.50632155  1512.38827015]
 [ 1512.38827015  4098.24280756]]
Matriz U:
 [[ 3.93968801]
 [-0.6012039 ]]
Matriz Xa:
 [[1065.25529366]
 [ 825.18662673]]


In [135]:
X.sum()

-7.233076544616712e-05

In [136]:
for i in range (1000) :
    X0=Xa
    L0=np.matrix([[(math.sqrt(((X1-X0[0][0])**2)+((Y1-X0[1][0])**2)))],
                  [(math.sqrt(((X2-X0[0][0])**2)+((Y2-X0[1][0])**2)))],
                  [(math.sqrt(((X3-X0[0][0])**2)+((Y3-X0[1][0])**2)))],
                  [(math.sqrt(((X4-X0[0][0])**2)+((Y4-X0[1][0])**2)))]]);
    A=np.zeros((4,2))
    A[0][0]=-(X1-X0[0][0])/Lb[0][0]
    A[0][1]=-(Y1-X0[1][0])/Lb[0][0]
    A[1][0]=-(X2-X0[0][0])/Lb[1][0]
    A[1][1]=-(Y2-X0[1][0])/Lb[1][0]
    A[2][0]=-(X3-X0[0][0])/Lb[2][0]
    A[2][1]=-(Y3-X0[1][0])/Lb[2][0]
    A[3][0]=-(X4-X0[0][0])/Lb[3][0]
    A[3][1]=-(Y4-X0[1][0])/Lb[3][0]
    L=L0-Lb
    N=np.dot(np.dot(A.T,P),A)
    #print("Matriz N:\n",N)
    U=np.dot(np.dot(A.T,P),L)
    #print("Matriz U:\n",U)
    X=-np.dot(np.linalg.inv(N),U)
    Xa=X0+X
    #print("Matriz Xa:\n",Xa)

In [137]:
X.sum()

-1.6155081644476324e-14

In [138]:
Xa

matrix([[1065.25529365],
        [ 825.18662675]])