In [9]:
## A matriz Lb é a matriz das observações:
import numpy as np
l1=201.71
l2=75.81
l3=125.22
l4=100.03
l5=100.76
Lb=np.matrix ([[l1],[l2],[l3],[l4],[l5]]);

In [10]:
# A matriz L0 e X0

X0=np.matrix ([[Lb[0,0]],
               [Lb[1,0]],
               [Lb[3,0]]])
L0=np.matrix([[(1*X0[0,0]+0*X0[1,0]+0*X0[2,0])],
              [(0*X0[0,0]+1*X0[1,0]+0*X0[2,0])],
              [(1*X0[0,0]-1*X0[1,0]+0*X0[2,0])],
              [(0*X0[0,0]+0*X0[1,0]+1*X0[2,0])],
              [(1*X0[0,0]+0*X0[1,0]-1*X0[2,0])]])


In [8]:
# A matriz A

A =np.matrix([[1,  0,  0],
              [0,  1,  0],
              [1, -1,  0],
              [0,  0,  1],
              [1,  0, -1]])

In [13]:
# matriz P

P=np.eye(5)
P

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Sistema de equações normais

L=L0-Lb
N=np.dot(np.dot(A.T,P),A)
print("Matriz N:\n",N)
U=np.dot(np.dot(A.T,P),L)
print("Matriz U:\n",U)
X=-np.dot(np.linalg.inv(N),U)
Xa=X0+X
print("Matriz Xa:\n",Xa)

Matriz N:
 [[ 3. -1. -1.]
 [-1.  2.  0.]
 [-1.  0.  2.]]
Matriz U:
 [[ 1.6 ]
 [-0.68]
 [-0.92]]
Matriz Xa:
 [[201.31]
 [ 75.95]
 [100.29]]
