<a href="https://colab.research.google.com/github/Alixandrini/ENGJ22/blob/main/Aula%207/Exerc%C3%ADcios_Correlato.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercícos Ajustamento Correlato

## Exercício 01
Ajustamento de uma rede de nivelamento. São conhecidas as altitudes dos pontos A, B e C.
Determinar as altitudes dos pontos I, II, III, IV e V. As setas do esquema indicam o sentido em
que o terreno se eleva. No quadro a seguir estão as observações e o esquema gráfico:

<img src="https://raw.githubusercontent.com/Alixandrini/ENGJ22/main/Aula%206/rede_ex1.png">

Altitudes conhecias: hA = 33,831m hB = 19,316m hC = 2,791m
Usar pesos inversamente proporcionais ao comprimento da linha nivelada.

| Linha | $\ \Delta$h (m) | Comprimento(km)|
|---------| ---------| ---------| 
| 1       | 10,038   |     1,14 |
| 2       |  8,297   |     2,84 |
| 3       |  1,949   |     3,21 |
| 4       |  5,217   |     6,03 |
| 5       | 10,244   |     6,75 |
| 6       |  1,562   |     0,84 |
| 7       |  4,837   |     2,94 |
| 8       |  3,370   |     2,01 |
| 9       | 15,979   |     5,28 |

###Resolução:
Vamos construir nosso sistema de equações:
\begin{equation}
l_{1a}+l_{2a}+l_{6a}-l_{8a}-(h_{B}-h_{C})=0 \\
-l_{9a}+l_{7a}-l_{8a}-(h_{B}-h_{A})=0 \\
l_{2a}+l_{3a}-l_{5a}=0 \\
l_{3a}-l_{4a}+l_{7a}-l_{6a} =0 \\
\end{equation}

In [ ]:
import numpy as np
ha=33.831;
hb=19.316;
hc=2.791;
Lb=np.matrix ([[10.038],[8.297],[1.949],[5.217],[10.244],[1.562],[4.837],[3.370],[15.979]]);
P=np.zeros((9,9))
P[0,0]=1.14**-1
P[1,1]=2.84**-1
P[2,2]=3.21**-1
P[3,3]=6.03**-1
P[4,4]=6.75**-1
P[5,5]=0.84**-1
P[6,6]=2.94**-1
P[7,7]=2.01**-1
P[8,8]=5.28**-1
B=np.matrix([[1,1,0,0,0,1,0,-1,0],
             [0,0,0,0,0,0,1,-1,-1],
             [0,1,1,0,-1,0,0,0,0],
             [0,0,1,-1,0,-1,1,0,0]]);

W=np.matrix([[(Lb[0,0]+Lb[1,0]+Lb[5,0]-Lb[7,0]-(hb-hc))],
             [(-Lb[8,0]+Lb[6,0]-Lb[7,0]-(hb-ha))],
             [(Lb[1,0]+Lb[2,0]-Lb[4,0])],
             [(Lb[2,0]-Lb[3,0]+Lb[6,0]-Lb[5,0])]]);

### Sistema de equacões normais para o método Correlato

In [ ]:
M=np.dot(np.dot(B,np.linalg.inv(P)),B.T)
K=np.dot(-np.linalg.inv(M),W)
V=np.dot(np.dot(np.linalg.inv(P),B.T),K)
La=Lb+V
La

matrix([[10.03757348],
        [ 8.29613241],
        [ 1.94740417],
        [ 5.22041175],
        [10.24353658],
        [ 1.56216099],
        [ 4.83516857],
        [ 3.37086688],
        [15.97930169]])

In [ ]:
#conferindo o resultado
Lb=La
W=np.matrix([[(Lb[0,0]+Lb[1,0]+Lb[5,0]-Lb[7,0]-(hb-hc))],
             [(-Lb[8,0]+Lb[6,0]-Lb[7,0]-(hb-ha))],
             [(Lb[1,0]+Lb[2,0]-Lb[4,0])],
             [(Lb[2,0]-Lb[3,0]+Lb[6,0]-Lb[5,0])]]);
W
#W tem que ter valores nulos

matrix([[3.55271368e-15],
        [0.00000000e+00],
        [0.00000000e+00],
        [4.44089210e-16]])

matrix([[0.002],
        [0.003],
        [0.002],
        [0.007]])

## Exercício 2
A medida de uma pequena base conduziu ao valor: l1 201,71m . Numa segunda experiência a base foi decomposta em duas e ambas medidas com o seguinte resultado: l2 75,81m e l3 125,22m. Na terceira experiência, idêntica a segunda, obteve-se: l4 100,03m e l5 100,76 m . Ajustar pelo método dos correlatos:

###resolução:
Criar nosso sistema de equações:
\begin{equation}
l_{1a}-l_{2a}-l_{3a}=0 \\
l_{1a}-l_{4a}-l_{5a}=0 \\
\end{equation}

In [ ]:
Lb=np.matrix([[201.71],[75.81],[125.22],[100.03],[100.76]]);
P=np.eye(5,5)
B=np.matrix([[1,-1,-1,0,0],
             [1,0,0,-1,-1]]);
W=np.matrix([[Lb[0,0]-Lb[1,0]-Lb[2,0]],
             [Lb[0,0]-Lb[3,0]-Lb[4,0]]]);


###Sistema de Equações normais

In [ ]:
M=np.dot(np.dot(B,np.linalg.inv(P)),B.T)
K=np.dot(-np.linalg.inv(M),W)
V=np.dot(np.dot(np.linalg.inv(P),B.T),K)
La=Lb+V
La

matrix([[201.31],
        [ 75.95],
        [125.36],
        [100.29],
        [101.02]])

In [ ]:
#conferindo o resultado
Lb=La
W=np.matrix([[Lb[0,0]-Lb[1,0]-Lb[2,0]],
             [Lb[0,0]-Lb[3,0]-Lb[4,0]]]);
W
#W tem que ter valores nulos

matrix([[ 0.00000000e+00],
        [-1.42108547e-14]])